* TrollDB

TrollDB is an in-memory JavaScript database which prioritises
performance over *everything*. It is blazingly fast. You *will not*
find a faster in-memory JavaScript Database, so stop looking. You've
arrived.

** Usage

First require the trolldb script:

#+BEGIN_SRC html
<script type="text/javascript" src="trolldb.js"></script>
#+END_SRC

*** Insert

You can insert any form of structured data you like:

#+BEGIN_SRC javascript
db.insert({"balance": 12345});
#+END_SRC

TrollDB will optimize this insert for performance.

*** Query

You can query for data with pattern matching.

#+BEGIN_SRC javascript
db.query({"balance": undefined});
#+END_SRC

TrollDB will optimize this query for performance.

*** Update

You can update data with pattern matching.

#+BEGIN_SRC javascript
db.update({"balance": undefined});
#+END_SRC

TrollDB will optimize this update for performance.

*** Delete

You can delete data with pattern matching.

#+BEGIN_SRC javascript
db.delete({"balance": undefined});
#+END_SRC

TrollDB will optimize this delete for performance.

** Bugs

Please report any bugs in the Github Issue tracker. Please note that
only bugs that affect performance will be considered bugs.

** Status

Production-ready, if performance is your only concern.

** Credits

Thanks to [[https://github.com/honza][Honza Pokorny]] for adding NodeJS support, and [[http://lokijs.org/#/][LokkiJS]] for the
inspiration.

** License

Copyright © 2014 Kris Jenkins

Distributed under the Eclipse Public License.
